comment_index:
    path:     /
    defaults: { _controller: "MediaBundle:Comment:index" }
    methods:  GET

comment_show:
    path:     /{id}/show
    defaults: { _controller: "MediaBundle:Comment:show" }
    methods:  GET

comment_new:
    path:     /new
    defaults: { _controller: "MediaBundle:Comment:new" }
    methods:  [GET, POST]



comment_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediaBundle:Comment:delete" }
    methods:  DELETE
